# Generated by Django 5.1.7 on 2025-08-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('locked', models.BooleanField(default=False)),
                ('winner', models.CharField(blank=True, max_length=50, null=True)),
                ('window_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
            ],
            options={
                'unique_together': {('week', 'home_team', 'away_team')},
            },
        ),
    ]
