# Generated by Django 5.1.7 on 2025-08-28 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(blank=True, db_index=True, null=True)),
                ('week', models.IntegerField()),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('locked', models.BooleanField(default=False)),
                ('winner', models.CharField(blank=True, max_length=50, null=True)),
                ('window_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
            ],
            options={
                'ordering': ['season', 'week', 'start_time'],
                'indexes': [models.Index(fields=['season', 'week'], name='game_season_week_idx'), models.Index(fields=['season', 'window_key'], name='game_season_window_idx'), models.Index(fields=['season', 'start_time'], name='game_season_start_idx')],
                'constraints': [models.UniqueConstraint(fields=('season', 'week', 'home_team', 'away_team'), name='uniq_game_per_season_week_matchup')],
            },
        ),
        migrations.CreateModel(
            name='PropBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('over_under', 'Over/Under'), ('point_spread', 'Point Spread'), ('take_the_bait', 'Take-the-Bait')], max_length=20)),
                ('question', models.CharField(max_length=255)),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.CharField(blank=True, max_length=50, null=True)),
                ('season', models.IntegerField(blank=True, db_index=True, null=True)),
                ('window_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_bets', to='games.game')),
            ],
            options={
                'indexes': [models.Index(fields=['season', 'window_key'], name='propbet_season_window_idx'), models.Index(fields=['game', 'season'], name='propbet_game_season_idx')],
                'constraints': [models.UniqueConstraint(fields=('game', 'question'), name='uniq_propbet_per_game_question')],
            },
        ),
    ]
