# Generated by Django 5.1.7 on 2025-03-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('locked', models.BooleanField(default=False)),
                ('winner', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
