# Generated by Django 5.1.7 on 2025-03-13 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('week', 'home_team', 'away_team')},
        ),
    ]
