# Generated by Django 5.1.7 on 2025-08-29 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWindowStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_correct', models.IntegerField(default=0)),
                ('pb_correct', models.IntegerField(default=0)),
                ('season_cume_points', models.IntegerField(default=0)),
                ('rank_dense', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='window_stats', to=settings.AUTH_USER_MODEL)),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='games.window')),
            ],
            options={
                'ordering': ['window_id', 'rank_dense', '-season_cume_points'],
                'indexes': [models.Index(fields=['window'], name='analytics_u_window__23ca51_idx'), models.Index(fields=['user', 'window'], name='analytics_u_user_id_71f014_idx')],
                'constraints': [models.UniqueConstraint(fields=('window', 'user'), name='uniq_user_window_stat')],
            },
        ),
    ]
