# Generated by Django 5.1.7 on 2025-08-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='UserWindowStat',
            name='rank_delta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='UserWindowStat',
            name='window_points',
            field=models.IntegerField(default=0),
        ),
    ]
